### ISSUE TITLE
feedack for DeBacker Biden campaign reform file

### ISSUE THREAD

**Issue by MattHJensen** [PSLmodels/examples#1]
From https://github.com/PSLmodels/Tax-Calculator/pull/2544#issuecomment-774148497 @Peter-Metz said: 

> Just wanted to flag that I seem to remember that the PT_qbid_* params were repurposed in Kyle/Erin/Grant's fork. You should be able to get the desired QBID phaseout with PT_qbid_ps and PT_qbid_prt. Also, when running the reform with the PUF or CPS, it may make sense to flip the PT_qbid_limit_switch to False to bypass the capital/wage limitations that depend on data that the PUF and CPS don't report.

> @erinmelly @grantseiter am I remembering correctly re: the PT_qbid_* params?

cc @jdebacker, @Peter-Metz, @erinmelly, @grantseiter

**Comment by erinmelly** [comment]
Yes, that is correct. For the work that @Peter-Metz is referencing, the qbid logic was modified to take away the capital and wage limitations.

**Comment by jdebacker** [comment]
Ok, I've replaced:

```
"PT_qbid_taxinc_thd": {"2021": [400000.00, 400000.00, 400000.00, 400000.00, 400000.00],
                           "2026": [0.0, 0.0, 0.0, 0.0, 0.0]},
"PT_qbid_taxinc_gap": {"2021": [100000.0, 100000.0, 100000.0, 100000.0, 100000.00],
                           "2026": [1.0, 1.0, 1.0, 1.0, 1.0]},
```

with

```
"PT_qbid_ps": {"2021": [400000.00, 400000.00, 400000.00, 400000.00, 400000.00],
                           "2026": [0.0, 0.0, 0.0, 0.0, 0.0]},
"PT_qbid_prt": {"2021": [1.0, 1.0, 1.0, 1.0, 1.0]},
"PT_qbid_limit_switch": {"2021": false},
```

Does this look right @MattHJensen @Peter-Metz @erinmelly ?

**Comment by Peter-Metz** [comment]
Hi Jason - is the idea to eliminate the QBI deduction in 2026? Although it won't change the results, I would considering removing the 2026 adjustment to `PT_qbid_ps` since `policy_current_law.json` already sets `PT_qbid_rt` to 0 in 2026. I think setting the phaseout threshold to 0 but maintaining a phaseout rate is a bit conceptually confusing.

**Comment by jdebacker** [comment]
@Peter-Metz Thanks for these comments. 

The proposal is to phase out the QBI deduction for incomes above $400,000 starting in 2021, then to have current law beginning in 2026 (which entails removing the QBI all together).  I don't see any details on the phaseout rate, so just set it at 100%, which seems consistent with other sharp increases in taxes for those with incomes over $400,000 found in the proposal.

Does the following look better to you? :

```
"PT_qbid_ps": {"2021": [400000.00, 400000.00, 400000.00, 400000.00, 400000.00]},
"PT_qbid_prt": {"2021": [1.0, 1.0, 1.0, 1.0, 1.0]},
"PT_qbid_limit_switch": {"2021": false},
```

**Comment by Peter-Metz** [comment]
Looks good to me!

**Comment by jdebacker** [comment]
Thank you all for your review!
