### ISSUE TITLE
Change tax year for recovery rebates from 2021 to 2020 or 2019

### ISSUE THREAD

**Issue by MaxGhenis** [PSLmodels/examples#6]
Recovery Rebates are based on 2019 or 2020 income, whichever is filed so far. Probably based on 2019 for most filers, though I think it will be based on 2020 income for people whose eligibility increased. @codykallen 

https://github.com/PSLmodels/examples/blob/49dce61d6cee211398a5124ed00a22d6775ee1f1/psl_examples/taxcalc/ARPA.json#L20-L25

**Comment by jdebacker** [comment]
@MaxGhenis This is tricky - the revenue hit will be in 2021, but because these rebates are based on 2020 liabilities, we shouldn't expect changes in MTRs in 2021.  Not sure how to handle that in Tax-Calculator other than some customization of the code for computing MTRs to take into account retroactive policies like this.

**Comment by MaxGhenis** [comment]
Doesn't seem too different from other refundable tax credits, which often affect revenue the year after their tax year. ARP's UI changes also will affect revenue in 2021, and are specified in the reform as being for the 2020 tax year. I think changing the rebates to 2020 would be the most consistent approach.

**Comment by codykallen** [comment]
@MaxGhenis, the calculation of the AGI limitation on the credit amount will be based on 2021 AGI. However, the initial payments being made now are based on 2019 or 2020 AGI.

**Comment by codykallen** [comment]
This could potentially result in some clawback of the credit when filing taxes for 2021. If an overpayment of the initial credit was made based on 2019 or 2020 income relative to the correct amount based on 2021 income, the this can be clawed back by reducing a tax refund, but the size of the tax refund limits this clawback. If the individual has no refund or owes money when they file, any overpayment of the rebate credit cannot be clawed back.

**Comment by MaxGhenis** [comment]
My mistake, thanks @codykallen. [This article](https://www.kitces.com/blog/the-american-rescue-plan-act-of-2021-tax-credits-stimulus-checks-and-more-that-advisors-need-to-know/) describes the three ARP rebate checkpoints:
1. Today, based mostly on 2019 income
2. Later this year, to capture 2020 income for most taxpayers
3. 2022 at filing time for 2021 tax year

It says there will be no clawbacks (rebates can only increase at each subsequent checkpoint), which probably means that most of the MTRs created by the rebates are retroactive. But it will still affect 2021 MTRs for filers who weren't eligible for the full amount based on 2019 or 2020 income, so keeping as-is sounds like the right call to me.
